SELECT
    pa.id,
    pa."uuid",
    pa.project_id,
    pa.project_name,
    pa.agency_id,
    pa.agency_name,
    pa.broad_activity_id,
    pa.broad_activity_name,
    pa.sub_activity_id,
    pa.sub_activity_name,
    pa.sub_activity_name_id,
    pa.sub_activity_type_name,
    pa.location_id,
    pa.location_name,
    pa.division_id,
    pa.division_name,
    pa.district_id,
    pa.district_name,
    pa.upazila_id,
    pa.upazila_name,
    pa.event_start_date,
    pa.demonstration_date,
    pa.input_distributation_date,
    pa.publication_start_date,
    pa.monitor_visit_date,
    pa.field_trial_date,
    pa.group_date,
    pa.tag_name,
    pa.user_id,
    pa.created_at,
    pa.updated_at,
    pa.deleted_at,
    pa.demo_type,
    pa."xml",
    pa.monitor_end_date,

    COUNT(DISTINCT b.id) AS total_members,
    COUNT(DISTINCT CASE WHEN b.gender_label = 'Male' THEN b.id END) AS male_members,
    COUNT(DISTINCT CASE WHEN b.gender_label = 'Female' THEN b.id END) AS female_members,
    COUNT(DISTINCT CASE WHEN b.age::bigint between 15 AND 34 THEN b.id END) AS youth_members,
    COUNT(DISTINCT CASE WHEN LOWER(b.house_hold_gender) = 'female' THEN b.id END) AS women_headed_households,
    COUNT(DISTINCT CASE WHEN b.ethnicity IS NOT NULL AND b.ethnicity != '1' THEN b.id END) AS ethnic_members

FROM core.project_activity pa 
JOIN core.sacp_project_members spm 
    ON pa.id = spm.project_uid::bigint
LEFT JOIN beneficiary b 
    ON spm.member_uid::bigint = b.id
LEFT JOIN core.sacp_groups_members sgm 
    ON sgm.member_uid::bigint = spm.member_uid::bigint

GROUP BY
    pa.id,
    pa."uuid",
    pa.project_id,
    pa.project_name,
    pa.agency_id,
    pa.agency_name,
    pa.broad_activity_id,
    pa.broad_activity_name,
    pa.sub_activity_id,
    pa.sub_activity_name,
    pa.sub_activity_name_id,
    pa.sub_activity_type_name,
    pa.location_id,
    pa.location_name,
    pa.division_id,
    pa.division_name,
    pa.district_id,
    pa.district_name,
    pa.upazila_id,
    pa.upazila_name,
    pa.event_start_date,
    pa.demonstration_date,
    pa.input_distributation_date,
    pa.publication_start_date,
    pa.monitor_visit_date,
    pa.field_trial_date,
    pa.group_date,
    pa.tag_name,
    pa.user_id,
    pa.created_at,
    pa.updated_at,
    pa.deleted_at,
    pa.demo_type,
    pa."xml",
    pa.monitor_end_date

ORDER BY pa.id DESC; 